[project]
name = "abc"
version = "0.1.0"
description = "Approximate Bayesian Computation - Final Project"
authors = [
  {name = "Christian Mancini", email = "christian.mancini@unifi.it"},
]
requires-python = "==3.14.*"
readme = "README.md"
license = "MIT"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "setuptools>=81.0.0",
    "torch>=2.11.0",
]

[tool.uv.sources]
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[project.urls]
Repository = "https://github.com/cMancio00/ABC.git"

[dependency-groups]
dev = [
    "ruff==0.15.10",
]
[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[build-system]
requires = ["setuptools >= 81.0.0"]
build-backend = "setuptools.build_meta"
